/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdicionarRouteImport } from './routes/adicionar'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BibliotecaRouteImport } from './routes/biblioteca'
import { Route as ClubesRouteImport } from './routes/clubes'
import { Route as ContaRouteImport } from './routes/conta'
import { Route as DesafioLiterarioRouteImport } from './routes/desafio-literario'
import { Route as DesejosRouteImport } from './routes/desejos'
import { Route as EmprestimosRouteImport } from './routes/emprestimos'
import { Route as EstatisticasRouteImport } from './routes/estatisticas'
import { Route as NotificacoesRouteImport } from './routes/notificacoes'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as RedefinirSenhaRouteImport } from './routes/redefinir-senha'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as AssinaturaRetornoRouteImport } from './routes/assinatura.retorno'
import { Route as ClubesClubIdRouteImport } from './routes/clubes_.$clubId'
import { Route as ClubesDescobrirRouteImport } from './routes/clubes_.descobrir'
import { Route as ClubesEntrarRouteImport } from './routes/clubes_.entrar'
import { Route as ClubesNovoRouteImport } from './routes/clubes_.novo'
import { Route as LivroIdRouteImport } from './routes/livro.$id'
import { Route as LivroIdSessaoRouteImport } from './routes/livro.$id_.sessao'
import { Route as LivroIdSessaoSessionIdRouteImport } from './routes/livro.$id_.sessao_.$sessionId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdicionarRoute = AdicionarRouteImport.update({
  id: '/adicionar',
  path: '/adicionar',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BibliotecaRoute = BibliotecaRouteImport.update({
  id: '/biblioteca',
  path: '/biblioteca',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubesRoute = ClubesRouteImport.update({
  id: '/clubes',
  path: '/clubes',
  getParentRoute: () => rootRouteImport,
} as any)
const ContaRoute = ContaRouteImport.update({
  id: '/conta',
  path: '/conta',
  getParentRoute: () => rootRouteImport,
} as any)
const DesafioLiterarioRoute = DesafioLiterarioRouteImport.update({
  id: '/desafio-literario',
  path: '/desafio-literario',
  getParentRoute: () => rootRouteImport,
} as any)
const DesejosRoute = DesejosRouteImport.update({
  id: '/desejos',
  path: '/desejos',
  getParentRoute: () => rootRouteImport,
} as any)
const EmprestimosRoute = EmprestimosRouteImport.update({
  id: '/emprestimos',
  path: '/emprestimos',
  getParentRoute: () => rootRouteImport,
} as any)
const EstatisticasRoute = EstatisticasRouteImport.update({
  id: '/estatisticas',
  path: '/estatisticas',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificacoesRoute = NotificacoesRouteImport.update({
  id: '/notificacoes',
  path: '/notificacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const RedefinirSenhaRoute = RedefinirSenhaRouteImport.update({
  id: '/redefinir-senha',
  path: '/redefinir-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const AssinaturaRetornoRoute = AssinaturaRetornoRouteImport.update({
  id: '/assinatura/retorno',
  path: '/assinatura/retorno',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubesClubIdRoute = ClubesClubIdRouteImport.update({
  id: '/clubes_/$clubId',
  path: '/clubes/$clubId',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubesDescobrirRoute = ClubesDescobrirRouteImport.update({
  id: '/clubes_/descobrir',
  path: '/clubes/descobrir',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubesEntrarRoute = ClubesEntrarRouteImport.update({
  id: '/clubes_/entrar',
  path: '/clubes/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubesNovoRoute = ClubesNovoRouteImport.update({
  id: '/clubes_/novo',
  path: '/clubes/novo',
  getParentRoute: () => rootRouteImport,
} as any)
const LivroIdRoute = LivroIdRouteImport.update({
  id: '/livro/$id',
  path: '/livro/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LivroIdSessaoRoute = LivroIdSessaoRouteImport.update({
  id: '/livro/$id_/sessao',
  path: '/livro/$id/sessao',
  getParentRoute: () => rootRouteImport,
} as any)
const LivroIdSessaoSessionIdRoute = LivroIdSessaoSessionIdRouteImport.update({
  id: '/livro/$id_/sessao_/$sessionId',
  path: '/livro/$id/sessao/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/adicionar': typeof AdicionarRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/biblioteca': typeof BibliotecaRoute
  '/clubes': typeof ClubesRoute
  '/conta': typeof ContaRoute
  '/desafio-literario': typeof DesafioLiterarioRoute
  '/desejos': typeof DesejosRoute
  '/emprestimos': typeof EmprestimosRoute
  '/estatisticas': typeof EstatisticasRoute
  '/notificacoes': typeof NotificacoesRoute
  '/privacidade': typeof PrivacidadeRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/termos': typeof TermosRoute
  '/assinatura/retorno': typeof AssinaturaRetornoRoute
  '/clubes/$clubId': typeof ClubesClubIdRoute
  '/clubes/descobrir': typeof ClubesDescobrirRoute
  '/clubes/entrar': typeof ClubesEntrarRoute
  '/clubes/novo': typeof ClubesNovoRoute
  '/livro/$id': typeof LivroIdRoute
  '/livro/$id/sessao': typeof LivroIdSessaoRoute
  '/livro/$id/sessao/$sessionId': typeof LivroIdSessaoSessionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/adicionar': typeof AdicionarRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/biblioteca': typeof BibliotecaRoute
  '/clubes': typeof ClubesRoute
  '/conta': typeof ContaRoute
  '/desafio-literario': typeof DesafioLiterarioRoute
  '/desejos': typeof DesejosRoute
  '/emprestimos': typeof EmprestimosRoute
  '/estatisticas': typeof EstatisticasRoute
  '/notificacoes': typeof NotificacoesRoute
  '/privacidade': typeof PrivacidadeRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/termos': typeof TermosRoute
  '/assinatura/retorno': typeof AssinaturaRetornoRoute
  '/clubes/$clubId': typeof ClubesClubIdRoute
  '/clubes/descobrir': typeof ClubesDescobrirRoute
  '/clubes/entrar': typeof ClubesEntrarRoute
  '/clubes/novo': typeof ClubesNovoRoute
  '/livro/$id': typeof LivroIdRoute
  '/livro/$id/sessao': typeof LivroIdSessaoRoute
  '/livro/$id/sessao/$sessionId': typeof LivroIdSessaoSessionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/adicionar': typeof AdicionarRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/biblioteca': typeof BibliotecaRoute
  '/clubes': typeof ClubesRoute
  '/conta': typeof ContaRoute
  '/desafio-literario': typeof DesafioLiterarioRoute
  '/desejos': typeof DesejosRoute
  '/emprestimos': typeof EmprestimosRoute
  '/estatisticas': typeof EstatisticasRoute
  '/notificacoes': typeof NotificacoesRoute
  '/privacidade': typeof PrivacidadeRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/termos': typeof TermosRoute
  '/assinatura/retorno': typeof AssinaturaRetornoRoute
  '/clubes_/$clubId': typeof ClubesClubIdRoute
  '/clubes_/descobrir': typeof ClubesDescobrirRoute
  '/clubes_/entrar': typeof ClubesEntrarRoute
  '/clubes_/novo': typeof ClubesNovoRoute
  '/livro/$id': typeof LivroIdRoute
  '/livro/$id_/sessao': typeof LivroIdSessaoRoute
  '/livro/$id_/sessao_/$sessionId': typeof LivroIdSessaoSessionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/adicionar'
    | '/admin'
    | '/auth'
    | '/biblioteca'
    | '/clubes'
    | '/conta'
    | '/desafio-literario'
    | '/desejos'
    | '/emprestimos'
    | '/estatisticas'
    | '/notificacoes'
    | '/privacidade'
    | '/redefinir-senha'
    | '/termos'
    | '/assinatura/retorno'
    | '/clubes/$clubId'
    | '/clubes/descobrir'
    | '/clubes/entrar'
    | '/clubes/novo'
    | '/livro/$id'
    | '/livro/$id/sessao'
    | '/livro/$id/sessao/$sessionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/adicionar'
    | '/admin'
    | '/auth'
    | '/biblioteca'
    | '/clubes'
    | '/conta'
    | '/desafio-literario'
    | '/desejos'
    | '/emprestimos'
    | '/estatisticas'
    | '/notificacoes'
    | '/privacidade'
    | '/redefinir-senha'
    | '/termos'
    | '/assinatura/retorno'
    | '/clubes/$clubId'
    | '/clubes/descobrir'
    | '/clubes/entrar'
    | '/clubes/novo'
    | '/livro/$id'
    | '/livro/$id/sessao'
    | '/livro/$id/sessao/$sessionId'
  id:
    | '__root__'
    | '/'
    | '/adicionar'
    | '/admin'
    | '/auth'
    | '/biblioteca'
    | '/clubes'
    | '/conta'
    | '/desafio-literario'
    | '/desejos'
    | '/emprestimos'
    | '/estatisticas'
    | '/notificacoes'
    | '/privacidade'
    | '/redefinir-senha'
    | '/termos'
    | '/assinatura/retorno'
    | '/clubes_/$clubId'
    | '/clubes_/descobrir'
    | '/clubes_/entrar'
    | '/clubes_/novo'
    | '/livro/$id'
    | '/livro/$id_/sessao'
    | '/livro/$id_/sessao_/$sessionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdicionarRoute: typeof AdicionarRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  BibliotecaRoute: typeof BibliotecaRoute
  ClubesRoute: typeof ClubesRoute
  ContaRoute: typeof ContaRoute
  DesafioLiterarioRoute: typeof DesafioLiterarioRoute
  DesejosRoute: typeof DesejosRoute
  EmprestimosRoute: typeof EmprestimosRoute
  EstatisticasRoute: typeof EstatisticasRoute
  NotificacoesRoute: typeof NotificacoesRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  RedefinirSenhaRoute: typeof RedefinirSenhaRoute
  TermosRoute: typeof TermosRoute
  AssinaturaRetornoRoute: typeof AssinaturaRetornoRoute
  ClubesClubIdRoute: typeof ClubesClubIdRoute
  ClubesDescobrirRoute: typeof ClubesDescobrirRoute
  ClubesEntrarRoute: typeof ClubesEntrarRoute
  ClubesNovoRoute: typeof ClubesNovoRoute
  LivroIdRoute: typeof LivroIdRoute
  LivroIdSessaoRoute: typeof LivroIdSessaoRoute
  LivroIdSessaoSessionIdRoute: typeof LivroIdSessaoSessionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adicionar': {
      id: '/adicionar'
      path: '/adicionar'
      fullPath: '/adicionar'
      preLoaderRoute: typeof AdicionarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biblioteca': {
      id: '/biblioteca'
      path: '/biblioteca'
      fullPath: '/biblioteca'
      preLoaderRoute: typeof BibliotecaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clubes': {
      id: '/clubes'
      path: '/clubes'
      fullPath: '/clubes'
      preLoaderRoute: typeof ClubesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conta': {
      id: '/conta'
      path: '/conta'
      fullPath: '/conta'
      preLoaderRoute: typeof ContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desafio-literario': {
      id: '/desafio-literario'
      path: '/desafio-literario'
      fullPath: '/desafio-literario'
      preLoaderRoute: typeof DesafioLiterarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desejos': {
      id: '/desejos'
      path: '/desejos'
      fullPath: '/desejos'
      preLoaderRoute: typeof DesejosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emprestimos': {
      id: '/emprestimos'
      path: '/emprestimos'
      fullPath: '/emprestimos'
      preLoaderRoute: typeof EmprestimosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estatisticas': {
      id: '/estatisticas'
      path: '/estatisticas'
      fullPath: '/estatisticas'
      preLoaderRoute: typeof EstatisticasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notificacoes': {
      id: '/notificacoes'
      path: '/notificacoes'
      fullPath: '/notificacoes'
      preLoaderRoute: typeof NotificacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redefinir-senha': {
      id: '/redefinir-senha'
      path: '/redefinir-senha'
      fullPath: '/redefinir-senha'
      preLoaderRoute: typeof RedefinirSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assinatura/retorno': {
      id: '/assinatura/retorno'
      path: '/assinatura/retorno'
      fullPath: '/assinatura/retorno'
      preLoaderRoute: typeof AssinaturaRetornoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clubes_/$clubId': {
      id: '/clubes_/$clubId'
      path: '/clubes/$clubId'
      fullPath: '/clubes/$clubId'
      preLoaderRoute: typeof ClubesClubIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clubes_/descobrir': {
      id: '/clubes_/descobrir'
      path: '/clubes/descobrir'
      fullPath: '/clubes/descobrir'
      preLoaderRoute: typeof ClubesDescobrirRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clubes_/entrar': {
      id: '/clubes_/entrar'
      path: '/clubes/entrar'
      fullPath: '/clubes/entrar'
      preLoaderRoute: typeof ClubesEntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clubes_/novo': {
      id: '/clubes_/novo'
      path: '/clubes/novo'
      fullPath: '/clubes/novo'
      preLoaderRoute: typeof ClubesNovoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/livro/$id': {
      id: '/livro/$id'
      path: '/livro/$id'
      fullPath: '/livro/$id'
      preLoaderRoute: typeof LivroIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/livro/$id_/sessao': {
      id: '/livro/$id_/sessao'
      path: '/livro/$id/sessao'
      fullPath: '/livro/$id/sessao'
      preLoaderRoute: typeof LivroIdSessaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/livro/$id_/sessao_/$sessionId': {
      id: '/livro/$id_/sessao_/$sessionId'
      path: '/livro/$id/sessao/$sessionId'
      fullPath: '/livro/$id/sessao/$sessionId'
      preLoaderRoute: typeof LivroIdSessaoSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdicionarRoute: AdicionarRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  BibliotecaRoute: BibliotecaRoute,
  ClubesRoute: ClubesRoute,
  ContaRoute: ContaRoute,
  DesafioLiterarioRoute: DesafioLiterarioRoute,
  DesejosRoute: DesejosRoute,
  EmprestimosRoute: EmprestimosRoute,
  EstatisticasRoute: EstatisticasRoute,
  NotificacoesRoute: NotificacoesRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  RedefinirSenhaRoute: RedefinirSenhaRoute,
  TermosRoute: TermosRoute,
  AssinaturaRetornoRoute: AssinaturaRetornoRoute,
  ClubesClubIdRoute: ClubesClubIdRoute,
  ClubesDescobrirRoute: ClubesDescobrirRoute,
  ClubesEntrarRoute: ClubesEntrarRoute,
  ClubesNovoRoute: ClubesNovoRoute,
  LivroIdRoute: LivroIdRoute,
  LivroIdSessaoRoute: LivroIdSessaoRoute,
  LivroIdSessaoSessionIdRoute: LivroIdSessaoSessionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
